services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi --log-file -
    envVars:
      - key: DEBUG
        value: 'False'
      - key: SECRET_KEY
        value: YOUR_SECRET_KEY_HERE
      - key: ALLOWED_HOSTS
        value: 'yourdomain.com,anotherdomain.com'
      - key: DB_NAME
        value: your_db_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: your_db_port


